services:
  mongo_db:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  app:
    build: 
      context: .
    ports:
      - 5000:80
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
    